version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:242201270868:task-definition/swiggy-td:1"
        LoadBalancerInfo:
          ContainerName: "swiggy"
          ContainerPort: 3000
